### ISSUE TITLE
Enhance accessibility of GLSP diagrams via keyboard

### ISSUE THREAD

**Issue by ndoschek** [eclipse-glsp/glsp#1029]
As part of a @aylin-sarioglu's diploma research conducted at the [Model Engineering lab](https://me.big.tuwien.ac.at/) of TU Wien in the [Business Informatics Group](https://www.big.tuwien.ac.at/), there are currently there are three main features planned to improve accessibility for GLSP diagrams:
- Keyboard support for searching elements (PR https://github.com/eclipse-glsp/glsp-client/pull/242)
- Keyboard support for resizing elements (PR https://github.com/eclipse-glsp/glsp-client/pull/240)
- Keyboard support for moving and zooming elements and viewport (PR https://github.com/eclipse-glsp/glsp-client/pull/241)

The following PRs are also planned as part of this great endeavour:
- Making the Tool Palette more accessible via the keyboard
- Improve Navigation (including user notifications, e.g. for different modes such as resize mode) (PR https://github.com/eclipse-glsp/glsp-client/pull/276)
- Shortcut-Helper (allows to register shortcuts and lists them in a help overlay) (PR https://github.com/eclipse-glsp/glsp-client/pull/260)
- Documentation (PRs: https://github.com/eclipse-glsp/glsp/pull/1036, https://github.com/eclipse-glsp/glsp-client/pull/254)

----
To do until the accessibility feature is completed (feel free to extract it out into own GH issues):
- [x] Provide additional accessibility module that we want to include by default (e.g. everything except grid selection on element creation, focus tracker and toast messages) and enable it as part of the defaults (follow-up issue #1128)
- [x] VS Code integration (follow-up issue #1129)
  - [ ] Externalize keyboard shortcuts into Theia-native keybindings to make them configurable for Theia users
  - [ ] Fix up styling of the help
  - [ ] Fix up visibility / styling of the focus tracker and toast messages
- [x] Theia integration (follow-up issue #1130)
  - [ ] Externalize keyboard shortcuts into Theia-native keybindings to make them configurable for Theia users
  - [ ] Fix up styling of the help
  - [ ] Fix up visibility / styling of the focus tracker and toast messages
- [x] Eclipse integration (follow-up issue #1131)
  - [ ] Externalize keyboard shortcuts into Theia-native keybindings to make them configurable for Theia users
  - [ ] Fix up styling of the help
  - [ ] Fix up visibility / styling of the focus tracker and toast messages

**Comment by tortmayr** [comment]
@martin-fleck-at Can this be closed?

**Comment by martin-fleck-at** [comment]
@tortmayr Afaik, yes. I don't think there is any work pending in this regard. I'll close the issue for now. @ndoschek If you expect more work to be done, please feel free to re-open.

**Comment by ndoschek** [comment]
Yes, there are still two features expected (as mentioned in the PR description). Hence I'll reopen this issue, one of those PRs was opened already.

**Comment by planger** [comment]
I added the open tasks into description but suggest we do the first task (provide default accessibility tool) rather soon, and extract separate issues for the platform integrations, so that we can close this task.
Thank you very much for this excellent work!

**Comment by ndoschek** [comment]
Closing this as the base of accessibility features for GLSP were completed in the scope of the standalone example.
For enabling accessibility features for the different integrations, follow-up issues were created (see description).
