### ISSUE TITLE
Switch to composite typescript build

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#1179]
We should consider updating your build setup in all ts repositories to use a composite typescript build that can be executed from the root
instead of the current lerna-> run build command in all packages approach.
Sprotty and Theia are also using composite typescript builds and this has a couple of advantages:

- All packages are consistently build with the same typescript version
- The build is a lot faster because only parts that have been changed are rebuild
- Typescript`s incremental build feature only works well with composite builds (currently we are just throwing a way the cached build info with every new build request)
- Watching uses a lot less resources. Instead of starting a watch process for each package individually we just have to start one in the root (and optionally for webpack bundles)

While we are at it we can also improve the linting setup. Currently we are streaming the lint command to all packages. This is not necessary because our eslint config is already available in the root so we could just execute one single lint command from the root.,

Repos:
- [x] glsp-client (https://github.com/eclipse-glsp/glsp-client/pull/328)
- [x] glsp-theia-integration (https://github.com/eclipse-glsp/glsp-theia-integration/pull/201)
- [x] glsp-vscode (https://github.com/eclipse-glsp/glsp-vscode-integration/pull/60)
- [x]  glsp-server-node  (https://github.com/eclipse-glsp/glsp-server-node/pull/79
- [x] glsp-eclipse-integration
- [x] glsp-playwright
