### ISSUE TITLE
Update to latest glsp dev config

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#1320]
Update all repos to use the latest glsp dev config

This includes
- Updating to the latest next version
- Refactoring of the `upgrade:next` command to use the new CLI command
- Add `generate:index` script that uses the new CLI command for auto index generation

While we are at it we could also run copyright header checks and prettier formatting to ensure that the code base is up to date

- [x] glsp-client (https://github.com/eclipse-glsp/glsp-client/pull/334)
- [x] glsp-server-node (https://github.com/eclipse-glsp/glsp-server-node/pull/80)
- [x] glsp-theia-integration (https://github.com/eclipse-glsp/glsp-theia-integration/pull/206)
- [x] glsp-eclipse-integration
- [x] glsp-playwright
- [x] glsp-vscode-integration (https://github.com/eclipse-glsp/glsp-vscode-integration/pull/61)

**Comment by tortmayr** [comment]
As part of this we should also consider
- Switching the CI pipeline to github actions (where possible)
- Use lerna-lite instead of lerna. This lightweight modular fork is more suitable for out needs as 
   - It does not have a dependency on nx (which we don't use at all)
   - Allows integration of only the lerna commands that we actually need (version, publish, run)
   - Main lerna has a bug in the `lerna run` command which causes the no-bail option to not work as expected. As a consequence
     our test command might exit early if there was a test error and does not captue the full scope of test cases. This is fixed in lerna-lite
