### ISSUE TITLE
Add Accessibility by Default

### ISSUE THREAD

**Issue by planger** [eclipse-glsp/glsp#1377]
## Goal
The goal of this epic is to add accessibility to standalone, VS Code, and Theia by default.

This includes:
- Keyboard navigation within the diagram
  - Panning
  - Navigating through the diagram with cursor keys (graphical, not necessarily semantical navigation)
  - Search
- Keyboard editing
  - Moving
  - Resizing
  - Renaming
  - Deleting
- Keyboard-enabled palette
  - Switching focus between diagram and palette (maybe with tab by default)
  - Enabling the search within the palette
  - Using the cursors to navigate between controls in the palette
 
As optional additional features, we may want to consider:
- Focus tracker widget indicating what is currently in focus
- Grid selection on element creation
- Toast messages

## Steps

Mostly this is about
1. splitting features into those that are on by default and optional features
2. applying the platform-specific keyboard and context key integrations to enable users changing the keyboard bindings in VS Code and Theia

## Issues
- [ ] https://github.com/eclipse-glsp/glsp/issues/1128
- [ ] https://github.com/eclipse-glsp/glsp/issues/1130
- [ ] https://github.com/eclipse-glsp/glsp/issues/1129

## Related but not in scope
- [ ] https://github.com/eclipse-glsp/glsp/issues/1131
