### ISSUE TITLE
Improve Container Support

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-glsp/glsp#1384]
## Goal
The goal of this epic is to ensure that the current support we have for containers and nested or structured components works as expected across all aspects of GLSP

This includes:
- Integration within the different layouts and their flags
- Tool support to re-parent elements
- Ensuring restriction and validations are considered

## Issues
- [ ] https://github.com/eclipse-glsp/glsp/issues/1235
- [ ] https://github.com/eclipse-glsp/glsp/issues/394

## Related but not in scope
- [ ] https://github.com/eclipse-glsp/glsp/issues/46
