### ISSUE TITLE
Cleanup API after DI rework

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#422]
With the changes of #150 large parts of the API can now be reworked. With the introduction of session-specific injectors it's no longer necesasry to keep track of the client id outside of the GLSPServer#process method. This means the entire action handler/ operation handler API can be reworked and simplified because the model state no longer has to be part of the method arguments and can be injected instead (see also #120). This is a umbrella ticket to track all parts of the APi that should be reworked.
From the top of my head:
- [x] rework Action/Operation handler API: Remove modelstate argument from handle() method & deprecate current implementation of the basic action/operation handlers. (eclipse-glsp/glsp/issues/425)
- [x] Filewatcher was previously scoped for multiple sessions and is now scoped for one client session. Check if the implementation requires cleanup. (Done, no changes required)
- [x] In many projects we use a mechanism to send action messages to the client "on-next-modelupdate" maybe we should add this functionality to the base framework. With the session-specific injectors its also guaranteed that the action messages are sent only on the next model update of this client session. (https://github.com/eclipse-glsp/glsp-server/pull/141)
- [x] Reconsider `ServerConnectionListener` API (#423)
- [x]  Remove model state argument from interface implementations and inject it instead to support arbitary model state classes (#120 
- [x] Clean up ActionDispatcher API (https://github.com/eclipse-glsp/glsp-server/pull/138)
