### ISSUE TITLE
Update example repository

### ISSUE THREAD

**Issue by tortmayr** [eclipse-glsp/glsp#477]
Update the glsp-example repository after the 0.9.0 release. We also want to provide the release version of the workflow dev example in addition to the minimal example. The workflow example then will also serve as the base for our planned migration guide that highlights the breaking changes in between releases and outline the necessary steps to upgrade the workflow example to the next release. This guide will serve as an entrypoint for adopters to easily identify the changes they need to make to their project for a successful update.

- [x] Update metadata
- [x] Move 0.8.0 workflow example to example repository. (#479)
- [x] Improve the developer setup for the example repository (#479)
- [x] Migrate minimal example to 0.9.0 (#449)
- [x] Migrate workflow example to 0.9.0 (https://github.com/eclipse-glsp/glsp-examples/pull/96/)
- [x] Create initial version of migration guide (#478)
